---
- id: packer_validate
  name: Packer Validate
  description: This hook runs `packer validate` on the directory
  entry: hooks/packer_validate.sh
  language: script
  pass_filenames: false
  verbose: true
  always_run: true

- id: packer_fmt
  name: Packer Format
  description: This hook runs `packer fmt` on the directory
  entry: hooks/packer_fmt.sh
  language: script
  pass_filenames: false
  verbose: true
  always_run: true
